# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: postgres
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    networks:
      - lib-db      
  
  rest-service:
    container_name: rest-service
    image: spiritforest/home-library:1.0
    restart: always
    environment:
      - PORT=$PORT
    ports:
      - $PORT:$PORT
    networks:
      - lib-db

networks:
  lib-db:
    driver: 'bridge'